name: Deploy mf_project_3 to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'packages/mf_project_3/**'
      - '.github/workflows/deploy-mf_project_3.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install

      - name: Build mf_project_3
        run: pnpm --filter mf_project_3 build

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd packages/mf_project_3
          wrangler pages deploy dist --project-name mf3-6sa
