name: Deploy mf_project_2 to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'packages/mf_project_2/**'
      - '.github/workflows/deploy-mf_project_2.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install dependencies
        run: pnpm install

      - name: Build mf_project_2
        run: pnpm --filter mf_project_2 build

      - name: Install Wrangler
        run: npm install -g @cloudflare/wrangler

      - name: Publish to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          # adjust output directory if your rsbuild outputs to a different folder
          wrangler pages publish packages/mf_project_2/dist --project-name mf2-8nl
